[package]
name = "cargo-bloat"
version = "0.7.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
description = "Find out what takes most of the space in your executable."
categories = ["development-tools::cargo-plugins"]
repository = "https://github.com/RazrFalcon/cargo-bloat"
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
goblin = "0.0.19" # the same version as in `object`
memmap = "0.7"
multimap = "0.5"
object = { version = "0.11", default-features = false, features = ["std", "compression"] }
regex = "1"
rustc-demangle = "0.1.6"
serde = "1"
serde_derive = "1"
serde_json = "1"
structopt = "0.2"
term_size = "0.3.1"
time = "0.1"
