[package]
name = "cargo-bloat"
version = "0.8.3"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
description = "Find out what takes most of the space in your executable."
categories = ["development-tools::cargo-plugins"]
repository = "https://github.com/RazrFalcon/cargo-bloat"
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
json = "0.11"
memmap = "0.7"
multimap = { version = "0.5", default-features = false }
pico-args = "0.2"
regex = { version = "1.2", optional = true }
term_size = "0.3.1"
time = "0.1"

[features]
regex-filter = ["regex"]
