[package]
name = "cargo-bloat"
version = "0.6.2"
authors = ["Reizner Evgeniy <razrfalcon@gmail.com>"]
description = "Find out what takes most of the space in your executable."
categories = ["development-tools::cargo-plugins"]
repository = "https://github.com/RazrFalcon/cargo-bloat"
readme = "README.md"
license = "MIT"

[dependencies]
goblin = "0.0.22" # the same version as in `object`
memmap = "0.7"
multimap = "0.4"
object = { version = "0.12", default-features = false, features = ["std", "compression"] }
regex = "1"
rustc-demangle = "0.1.6"
serde = "1"
serde_derive = "1"
serde_json = "1"
structopt = "0.2"
term_size = "0.3.1"
